---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: navya1
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    author: navya1
    type: proxy
      
