---
apiVersion: v1
kind: Service
metadata: 
    name: httpd-service
    labels:
      author: navya1
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
      type: webserver


