---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
spec:
  replicas: 1
  selector:
    matchLabels:
       type: appserver
  template:
    metadata:
       name: tomcat-pod
       labels:
         type: appserver
    spec:
       containers:
         - name: mytomcat
           image: tomee
       tolerations:
         - key: slave
           operator: Equal
           value: navya
           effect: NoSchedule

